services:
  latex_compiler:
    build:
      context: . # Specifica che il contesto di build è la directory corrente
      dockerfile: Dockerfile # Specifica il nome del Dockerfile
    volumes:
      - .:/cv_src # Monta la directory corrente in /cv_src del container
    command: /cv_src/compile_cv.sh resume_cv.tex
    # Rimuove automaticamente il container dopo l'esecuzione
    restart: "no"
    # Note: docker-compose non ha una direttiva 'rm' come 'docker run --rm'.
    # Per ottenere lo stesso comportamento, esegui il servizio con:
    # docker-compose run --rm latex_compiler
